// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcosdwzkiedxmjvifrfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjb3Nkd3praWVkeG1qdmlmcmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODQwNzMsImV4cCI6MjA3MDI2MDA3M30.jp3MBln0rCBxXNshqFg81lPxFEqsQXygpQiuHcrox0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});